// Generated by https://quicktype.io

export interface Reddit {
    rss: RSS;
}

export interface RSS {
    $:       RSSClass;
    channel: Channel[];
}

export interface RSSClass {
    "xmlns:media": string;
    "xmlns:atom":  string;
    "xmlns:dc":    string;
    version:       string;
}

export interface Channel {
    title:       string[];
    description: string[];
    pubDate:     string[];
    generator:   string[];
    link:        string[];
    "atom:link": AtomLinkElement[];
    image:       Image[];
    item:        Item[];
}

export interface AtomLinkElement {
    $: AtomLink;
}

export interface AtomLink {
    href: string;
    rel:  string;
    type: string;
}

export interface Image {
    link:  string[];
    url:   string[];
    title: string[];
}

export interface Item {
    title:        string[];
    link:         string[];
    description:  string[];
    "dc:creator": string[];
    pubDate:      string[];
    guid:         string[];
}
